name: Tolboe Capital
layout_spectrum: 0.0013408227823674679
typography_spectrum: 0.9503647212404758
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.04811177775263786
  lightness: 0.7021129115018994
  saturation: 0.9242191819939762
  rhythmicContrast: 0.6921449906658381
purpose: []
title: Tolboe Photography
description: ''
author:
  name: Andrew Tolboe
  url: 'http://www.tolboe.com'
  email: andrew@tolboe.com
content_rating:
  adult: false
content: []
github: true
