name: Tolboe Capital
favicon: null
layout_spectrum: 0.0013408227823674679
typography_spectrum: 0.9503647212404758
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.04811177775263786
  lightness: 0.7021129115018994
  saturation: 0.9242191819939762
  rhythmicContrast: 0.6921449906658381
purpose: []
